//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jewelly.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int ID { get; set; }
        public string Product_name { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Img { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string ImgPath { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<int> User_id { get; set; }
    
        public virtual ItemMst ItemMst { get; set; }
        public virtual UserRegMst UserRegMst { get; set; }
    }
}
